using System;

namespace randonNumber
{
    class Program
    {
    

        static void Main(string[] args)
        {

            Random ranNum = new Random();
            int hidenNumber = ranNum.Next(1, 3);
            int matchNumber;

            Console.WriteLine("Welcome to the \"Rock\" \"Paper\" and \"Scissors\" game.\n");
            Console.WriteLine("Please choose: Number 1 for Rock, Number 2 for Paper and Number 3 for Scissors and press enter:");
            matchNumber = Convert.ToInt32(Console.ReadLine());



            // Prints user's input and shows a message according to the choice shown 
            if (matchNumber == 1)
            {
                Console.WriteLine("\nPlayer chose: \"Rock\"");
            }

            else if (matchNumber == 2)
            {
                Console.WriteLine("\nPlayer chose: \"Paper\"");
            }

            else if (matchNumber == 3)
            {
                Console.WriteLine("\nPlayer chose: \"Scissors\"");
            }
            else
            {
                Console.WriteLine("Invalid input");
                
            } 


            //Prints the integer generated by the Ramdom number "RanNum"

            if (hidenNumber == 1)
            {
                Console.WriteLine("\nThe computer chose: \"Rock\"");
            }
            else if (hidenNumber == 2)
            {
                Console.WriteLine("\nThe computer chose: \"Paper\"");
            }
            else if (hidenNumber == 3)
            {
                Console.WriteLine("\nThe computer chose: \"Scissors\"");
            }
            else if (hidenNumber >= 4)
            {
                Console.WriteLine("Invalid input");
            }

           




            if (matchNumber == 1 && hidenNumber == 2)
                {

                    Console.WriteLine("Computer wins:  paper wins against rock ");

                }

                else if (matchNumber == 2 && hidenNumber == 1)
                {
                    Console.WriteLine("\n Paper wins!");
                }

                else if (matchNumber == 3 && hidenNumber == 2)
                {
                    Console.WriteLine("\n Scissors wins!");
                }
                else if (matchNumber == 3 && hidenNumber == 1)
                {
                    Console.WriteLine("\n Rock wins!");
                }
                else if ((matchNumber == 1 && hidenNumber == 1) || (matchNumber == 2 && hidenNumber == 2) || (matchNumber == 3 && hidenNumber == 3))
                {
                    Console.WriteLine("\n Wowooooo It is a tie!!!!");
                }


        }
    }
}
        
    

